apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocktwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocktwo
  template:
    metadata:
      labels:
        app: mocktwo
    spec:
      serviceAccountName: telemetry-access  # See below
      containers:
      - name: fastapi-container
        image: us-central1-docker.pkg.dev/project-bf98a213-f2fa-44da-a85/my-repo/mocktwo
        ports:
        - containerPort: 8200
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8200
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
